#!/bin/sh
fakepacdb="${fakepacdb:-/tmp/.localsync/}"
mkdir -p "$fakepacdb" &>/dev/null
ln -s /var/lib/pacman/local "$fakepacdb" &>/dev/null
fakeroot pacman -Sqy --dbpath "$fakepacdb" &>/dev/null

echo $(pacman -Qqu --dbpath "$fakepacdb" | wc -l) > /tmp/pacman_updates
